
import java.awt.Label;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sanket
 */
public class ArithCodingUI extends javax.swing.JFrame {
    private boolean fileSelect;
    JFileChooser loadFile;
    byte[] source,compressed,s,c;
    PrintWriter writer;
    String filename,parent;
    Double inlen,outlen;
    /**
     * Creates new form ArithCodingUI
     */
    public ArithCodingUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Compress");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Decompress");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    loadFile= new JFileChooser("C:\\Users\\Sanket\\Desktop");
    loadFile.setApproveButtonText("Select File");
    loadFile.setAcceptAllFileFilterUsed(false);
    FileNameExtensionFilter f1 = new FileNameExtensionFilter("Text Files", "txt", "text","rtf","doc","docx");
    loadFile.setFileFilter(f1);
   inlen=0.0;
   outlen=0.0;
    switch (loadFile.showOpenDialog(ArithCodingUI.this))
             {
                case JFileChooser.APPROVE_OPTION:

                    JOptionPane.showMessageDialog(ArithCodingUI.this, "Selection Successfull!","Attention!",JOptionPane.OK_OPTION);

                   jButton1.setText("File Chosen");
                    filename = String.valueOf(loadFile.getSelectedFile().getName());
                    parent = String.valueOf(loadFile.getSelectedFile().getParent());
                   jLabel1.setText(filename);
                   File filePath1 = loadFile.getSelectedFile();
                 
                    try {
                         
                        BufferedReader in = new BufferedReader(new FileReader(filePath1));
                        writer  = new PrintWriter(parent+"\\compressed","UTF-8");
                        char[] line = new char[500000];
                        while (in.read(line)>0) {
                            source=new String(line).getBytes("UTF-8");
                            //jTextArea1.append("got:\t"+new String(source,"UTF-8") + "\n");
                            compressed=Compressor.compress(source);
                            writer.println(compressed);
                            //.append(compressed + "\n");
                            c=Compressor.decompress(compressed);
                            String converted = new String(c,"UTF-8");
                            jTextArea1.append("to:\t"+new String(c,"UTF-8"));
                            
                            inlen+=source.length;
                            outlen+=compressed.length;
                        }
                        in.close();
                        writer.close();
                        jLabel2.setText("compression: "+ outlen*+100/inlen + "%");
                    } catch (IOException ex) {
                        System.err.println("Open plaintext error: " + ex);
                    }
            break;

                case JFileChooser.CANCEL_OPTION:
                   JOptionPane.showMessageDialog(ArithCodingUI.this, "No file chosen","Attention!",JOptionPane.OK_OPTION);
                   loadFile.setSelectedFile(null);
                   jButton1.setText("Browse..");
                   jLabel1.setText("Choose file to encrypt");
                   break;

                case JFileChooser.ERROR_OPTION:JOptionPane.showMessageDialog(ArithCodingUI.this, "Error","Choosing File",JOptionPane.OK_OPTION);
                   loadFile.setSelectedFile(null);
                   jButton1.setText("Browse..");
                   jLabel1.setText("Choose file to encrypt");
             }
    loadFile.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     try{
         jTextArea1.append("\n==================================\n");
         File fileToRead = new File(parent+"\\compressed");
                 
        BufferedReader in = new BufferedReader(new FileReader(fileToRead));
                        writer  = new PrintWriter(parent+"\\c\\"+filename);
                        String line = null;
                        
                        while ((line = in.readLine()) != null) {
                            //System.out.println(line);
                            s=line.getBytes("UTF-8");
                            jTextArea1.append("got:"+line + "\n");
                            c=Compressor.decompress(s);
                            writer.println(c.toString());
                            jTextArea1.append("made"+new String(c,"UTF-8") + "\n");
                        }
                        in.close();
                        writer.close();
                    } catch (IOException ex) {
                        System.err.println("Open plaintext error: " + ex);
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArithCodingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArithCodingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArithCodingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArithCodingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArithCodingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
